### ISSUE TITLE
Translation error? あの人 vs この人 This vs That. 1708637439859

### ISSUE THREAD

**Issue by Paulo-Nunes** [donkuri/Kaishi#53]
For Card ID: 1708637439859
あの人はいい人です。Translates to "This person is a good person."
My understanding is that あの means "That" and この means "This"

So the Translation, I would argue, should be "That person (over there) is a good person."

See この, その, あの, and どの 
![image](https://github.com/user-attachments/assets/b01aa31e-a641-4502-8d4f-bb611645ffdc)

Also found same translation for card ID: 1708637439860

**Comment by donkuri** [comment]
This was discussed before. While it is correct, people rarely say "That person over there", and あの itself is often used when someone is far from both people. こそあど is a complicated topic and should be discussed more in a grammar book.

**Comment by Paulo-Nunes** [comment]
If it has been discussed before, it might be an indicator that a note should be added to clarify confusion.

I have only gone so far as to complete Genki 1&2 and a little of Tobira a few years ago, but I do not recall seeing this exception mentioned. A quick glance at "A dictionary of Advanced Japanese Grammar's" index does not result in any item for こそあど words.

This may be the idiomatic vs grammatical argument, but it could cause confusion for people that are not in the know.

While I agree that "That person over there" is not natural (and why I had "over there" in parenthesis in the original comment), I would argue that "That person" is natural and a more accurate translation than "This person."

All that being said, I think a note is reasonable.

**Comment by donkuri** [comment]
While you are right in the sense that あ- is used for objects that are further from both the speaker and the listener, I don't think this is particularly important, in the same way that in English the demonstratives 'this' and 'that' are often interchanged. In other words, even in Japanese this distinction is not as important as beginners seem to think it is.

As I have said before, Kaishi is meant to have you focus on words, the sentences are only there to get you started and I don't think grammatical notes (because yes, こそあど is grammar) is very sensible.

In that sense, I don't mind changing it to 'that' instead of 'this', but you should keep in mind that this really is not that fundamental. I am not adding grammar notes however.

For a complete discussion of こそあど, please see the first chapter of [this book](https://www.3anet.co.jp/np/books/4680/).

**Comment by donkuri** [comment]
I have modified the cards for 人 and いい to change from 'this' to 'that', thank you! This will be released in the next batch of bug fixes. 👍
